version: '3.3'

volumes:
  static:
  bd:
  static_frontend:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - bd:/var/lib/postgresql/data

  backend:
    image: areshok/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - ./data/:/app/data/
    depends_on:
      - db

  frontend:
    image: areshok/foodgram_frontend
    volumes:
      - static_frontend:/app/result_build/

  nginx:
    image: areshok/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - static_frontend:/static_frontend/
    depends_on: 
      - backend
      - frontend
