# Generated by Django 3.2 on 2023-09-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ingredients',
            field=models.ManyToManyField(related_name='r_ingridient', through='receipt.IngredientReceipt', to='receipt.Ingredient'),
        ),
    ]
