# Generated by Django 3.2 on 2023-09-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_receipt', to='receipt.receipt'),
        ),
    ]
