# Generated by Django 3.2 on 2023-09-07 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipt.receipt'),
        ),
    ]
