# Generated by Django 3.2 on 2023-09-08 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0007_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientreceipt',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_i', to='receipt.ingredient'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_sp', to='receipt.receipt'),
        ),
    ]
