# Generated by Django 3.2 on 2023-09-08 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_auto_20230908_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient_i', to='receipt.receipt'),
        ),
    ]
