# Generated by Django 3.2 on 2023-09-26 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredientreceipt',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientreceipt_ingridient', to='receipt.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ingredients',
            field=models.ManyToManyField(related_name='receipt_ingridient', through='receipt.IngredientReceipt', to='receipt.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_receipt', to='receipt.receipt', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
