# Generated by Django 3.2 on 2023-09-28 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ingredients',
            field=models.ManyToManyField(related_name='receipt_ingredient', through='receipt.IngredientReceipt', to='receipt.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tags',
            field=models.ManyToManyField(through='receipt.TagReceipt', to='receipt.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='ingredientreceipt',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientreceipt_ingredient', to='receipt.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='ingredientreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientreceipt_receipt', to='receipt.receipt', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favoritesreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritesreceipt_receipt', to='receipt.receipt', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favoritesreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritesreceipt_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='tagreceipt',
            constraint=models.UniqueConstraint(fields=('tag', 'receipt'), name='unique_tagreceipt'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('receipt', 'user'), name='unique_shoppinglist'),
        ),
        migrations.AddConstraint(
            model_name='ingredientreceipt',
            constraint=models.UniqueConstraint(fields=('ingredient', 'receipt'), name='unique_ingredientreceipt'),
        ),
        migrations.AddConstraint(
            model_name='favoritesreceipt',
            constraint=models.UniqueConstraint(fields=('receipt', 'user'), name='unique_favoritesreceipt'),
        ),
    ]
