# Generated by Django 3.2 on 2023-09-19 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rf_receipt', to='receipt.receipt'),
        ),
        migrations.AlterField(
            model_name='favoritesreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
